//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.11 at 02:27:12 PM EET 
//


package com.sabanin;

import java.math.BigDecimal;
import java.util.Calendar;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for BankDepositeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BankDepositeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Country" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Type">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="�� �������������"/>
 *               &lt;enumeration value="�������"/>
 *               &lt;enumeration value="���������"/>
 *               &lt;enumeration value="�������������"/>
 *               &lt;enumeration value="��������������"/>
 *               &lt;enumeration value="�������������"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Depositor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AccountId" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="AmountOnDeposit">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;minExclusive value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Profitability">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="\d%"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *       &lt;/sequence>
 *       &lt;attribute name="depositeId" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BankDepositeType", propOrder = {
    "name",
    "country",
    "type",
    "depositor",
    "accountId",
    "amountOnDeposit",
    "profitability",
    "date"
})
public class BankDeposite {

    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "Country", required = true)
    protected String country;
    @XmlElement(name = "Type", required = true)
    protected String type;
    @XmlElement(name = "Depositor", required = true)
    protected String depositor;
    @XmlElement(name = "AccountId", required = true)
    protected BigDecimal accountId;
    @XmlElement(name = "AmountOnDeposit", required = true)
    protected BigDecimal amountOnDeposit;
    @XmlElement(name = "Profitability", required = true)
    protected String profitability;
    @XmlElement(name = "Date", required = true)
    @XmlSchemaType(name = "date")
    protected Calendar date;
    @XmlAttribute(name = "depositeId", required = true)
    protected BigDecimal depositeId;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountry(String value) {
        this.country = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the depositor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepositor() {
        return depositor;
    }

    /**
     * Sets the value of the depositor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepositor(String value) {
        this.depositor = value;
    }

    /**
     * Gets the value of the accountId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAccountId() {
        return accountId;
    }

    /**
     * Sets the value of the accountId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAccountId(BigDecimal value) {
        this.accountId = value;
    }

    /**
     * Gets the value of the amountOnDeposit property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAmountOnDeposit() {
        return amountOnDeposit;
    }

    /**
     * Sets the value of the amountOnDeposit property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAmountOnDeposit(BigDecimal value) {
        this.amountOnDeposit = value;
    }

    /**
     * Gets the value of the profitability property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProfitability() {
        return profitability;
    }

    /**
     * Sets the value of the profitability property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProfitability(String value) {
        this.profitability = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public Calendar getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDate(Calendar value) {
        this.date = value;
    }

    /**
     * Gets the value of the depositeId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDepositeId() {
        return depositeId;
    }

    /**
     * Sets the value of the depositeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDepositeId(BigDecimal value) {
        this.depositeId = value;
    }
    
    @Override
    public String toString(){
        StringBuffer result = new StringBuffer();
        result.append(name).append(" ");
        result.append(country).append(" ");
        result.append(type).append(" ");
        result.append(depositor).append(" ");
        result.append(accountId.toString()).append(" ");
        result.append(amountOnDeposit.toString()).append(" ");
        result.append(profitability).append(" ");
        result.append(depositeId.toString()).append("\n");
        return new String(result);
    }
}
